#okta:
#  oauth2:
#    issuer: https://dev-76857396.okta.com/oauth2/default
#    client-id: ${OKTA_CLIENT_ID}
#    client-secret: ${OKTA_CLIENT_SECRET}
#    redirect-uri: "/authorization-code/callback"